# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'frameworks/kwidgetsaddons' : '@latest'
    'pim/kmime' : '@same'
    'pim/kmbox' : '@same'
    'pim/libkleo' : '@same'

Options:
  require-passing-tests-on: ['Linux']
  gcovr-arguments: '--exclude "_install/.*" --exclude "examples/.*"'
