# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kcalendarcore': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/kirigami': 'Frameworks/6.24'
    'pim/kmime': '@same'
    'pim/kmbox': '@same'
    'pim/libkleo': '@same'

Options:
 require-passing-tests-on: ['@all']
 gcovr-arguments: '--exclude "_install/.*" --exclude "examples/.*"'
 run-qmllint: true
